Remove macOS executable signing

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -189,40 +189,18 @@ jobs:
         cd build
         cpack --verbose
 
-    - name: '🪪 Import Certificates'
-      uses: alex-spataru/import-codesign-certs@v4
-      with:
-        p12-file-base64: ${{secrets.APPLE_CERTIFICATES_P12}}
-        p12-password: ${{secrets.APPLE_CERTIFICATES_P12_PASSWORD}}
-
     - name: '💿 Mount DMG and copy application'
       run: |
         VOLUME=$(yes | hdiutil attach ./build/*.dmg -nobrowse | grep "Volumes" | awk '{print $3}')
         cp -a "$VOLUME/${{env.EXECUTABLE}}.app" "${{env.APPLICATION}}.app"
         hdiutil detach "$VOLUME"
-
-    - name: '✍🏻 Sign Application'
-      run: codesign --force --deep --options runtime --sign "${{secrets.APPLE_APPID_TEAM_ID}}" "${{env.APPLICATION}}.app"
         
     - name: '💽 Create nice DMG'
       run: |
         npm install --global create-dmg
         rm LICENSE.md
-        create-dmg "${{env.APPLICATION}}.app" --dmg-title="${{env.APPLICATION}}"
+        create-dmg "${{env.APPLICATION}}.app" --dmg-title="${{env.APPLICATION}}" || true  # Hack to allow DMG code signing to fail
         mv "${{env.APPLICATION}} ${{env.VERSION}}.dmg" "${{env.EXECUTABLE}}-${{env.VERSION}}-macOS-Universal.dmg"
-
-    - name: '📋 Notarize'
-      uses: wpilibsuite/xcode-notarize@v3
-      with:
-        product-path: ${{env.EXECUTABLE}}-${{env.VERSION}}-macOS-Universal.dmg
-        appstore-connect-username: ${{secrets.APPLE_NOTARIZATION_USERNAME}}
-        appstore-connect-teamid: ${{secrets.APPLE_NOTARIZATION_TEAMID}}
-        appstore-connect-password: ${{secrets.APPLE_NOTARIZATION_PASSWORD}}
-
-    - name: '📌 Staple'
-      uses: BoundfoxStudios/action-xcode-staple@v1
-      with:
-        product-path: ${{env.EXECUTABLE}}-${{env.VERSION}}-macOS-Universal.dmg
 
     - name: '📤 Upload artifact: DMG'
       uses: actions/upload-artifact@v4
